(ns axiescope.moves)

(defn tank-part-score
  [part-id]
  (case part-id
    "tail-hot-butt" 4
    "tail-tiny-dino" 4
    "back-pumpkin" 4
    "back-red-ear" 4
    "horn-rose-bud" 4
    "horn-beech" 4
    "mouth-zigzag" 4
    "mouth-herbivore" 4
    "tail-carrot" 3
    "tail-cattail" 3
    "tail-thorny-caterpillar" 3
    "back-hermit" 3
    "back-sponge" 3
    "back-indian-star" 3
    "back-snail-shell" 3
    "back-shiitake" 3
    "horn-cerastes" 3
    "horn-cactus" 3
    "horn-leafbug" 3
    "mouth-serious" 3
    "mouth-silence-whisper" 3
    "tail-hatsune" 2
    "tail-ant" 2
    "tail-feather-fan" 2
    "tail-potato-leaf" 2
    "tail-wall-gecko" 2
    "tail-gila" 2
    "tail-grass-snake" 2
    "tail-snake-jar" 2
    "tail-fish-snack" 2
    "back-bidens" 2
    "back-mint" 2
    "back-timber" 2
    "horn-bamboo-shoot" 2
    "horn-merry" 2
    "horn-ncisor" 2
    "horn-watermelon" 2
    "mouth-razor-bite" 2
    "mouth-toothless-bite" 2
    "mouth-tiny-turtle" 2
    "tail-koi" 1
    "back-bone-sail" 1
    "horn-lagging" 1
    "mouth-lam" 1
    "tail-pupae" 1
    "back-turnip" 1
    "horn-scaly-spear" 1
    "mouth-pincer" 1
    "tail-shrimp" 1
    "back-anemone" 1
    "horn-teal-shell" 1
    "mouth-piranha" 1
    "back-croc" 1
    "horn-abylonia" 1
    "mouth-riskyfish" 1
    "tail-navaga" 1
    "back-green-thorns" 1
    "horn-pliers" 1
    "tail-nimo" 1
    "back-watering-can" 1
    "horn-scaly-spoon" 1
    0))

(defn dps-part-score
  [part-id]
  (case part-id
    "tail-the-last-one" 4
    "back-tri-feather" 4
    "horn-eggshell" 4
    "mouth-little-owl" 4
    "tail-post-flight" 4
    "back-kingfisher" 4
    "horn-cactus" 4
    "mouth-nut-cracker" 4
    "tail-hare" 4
    "back-ronin" 4
    "horn-feather-spear" 4
    "mouth-doubletalk" 4
    "horn-little-branch" 4
    "horn-imp" 4
    "tail-swallow" 3
    "back-raven" 3
    "horn-trump" 3
    "mouth-peace-maker" 3
    "tail-shiba" 3
    "back-cupid" 3
    "horn-wing-horn" 3
    "mouth-hungry-bird" 3
    "tail-gerbil" 3
    "back-scarab" 3
    "horn-cuckoo" 3
    "mouth-axie-kiss" 3
    "tail-nut-cracker" 3
    "back-furball" 3
    "horn-shoal-star" 3
    "mouth-cute-bunny" 3
    "tail-cloud" 3
    "back-risky-beast" 3
    "horn-scaly-spear" 3
    "mouth-tiny-turtle" 3
    "tail-navaga" 3
    "back-jaguar" 3
    "horn-cerastes" 3
    "mouth-razor-bite" 3
    "tail-iguana" 3
    "back-hero" 3
    "horn-arco" 3
    "mouth-toothless-bite" 3
    "tail-shrimp" 3
    "tail-granmas-fan" 2
    "back-pigeon-post" 2
    "horns-pocky" 2
    "mouth-goda" 2
    "tail-tadpole" 2
    "back-bone-sail" 2
    "horn-pliers" 2
    "mouth-kotaro" 2
    "tail-cottontail" 2
    "back-perch" 2
    "horn-dual-blade" 2
    "mouth-piranha" 2
    "tail-nimo" 2
    "back-balloon" 2
    "horn-lagging" 2
    "mouth-risky-fish" 2
    "tail-ranchu" 2
    "back-blue-moon" 2
    "horn-parasite" 2
    "tail-rice" 2
    "back-goldfish" 2
    "horn-kestrel" 2
    "tail-grass-snake" 2
    "back-tri-spikes" 2
    "horn-bumpy" 2
    "back-spiky-wing" 2
    "horn-babylonia" 2
    "horn-beech" 2
    "horn-bamboo-shoot" 2
    "tail-snake-jar" 1
    "back-anemone" 1
    "horn-teal-shell" 1
    "mouth-catfish" 1
    "tail-koi" 1
    "back-roc" 1
    "horn-merry" 1
    "mouth-lam" 1
    "tail-hot-butt" 1
    "back-garish-worm" 1
    "horn-clamshell" 1
    "mouth-herbivore" 1
    "back-green-thorns" 1
    "mouth-serious" 1
    "horn-anemone" 1
    "horn-scaly-spoon" 1
    "mouth-square-teeth" 1
    "horn-incisor" 1
    "horn-oranda" 1
    "horn-unko" 1
    "horn-watermelon" 1
    "horn-antenna" 1
    "horn-caterpillars" 1
    0))
